### ISSUE TITLE
Create a basic wireframe for the project

### ISSUE THREAD

**Issue by vilbergs** [vilbergs/homebase#3]
We should probably agree on some type of basic interface structure before starting to hack away. It doesn't have to be too advanced, just something to lean on for now.

**Comment by AndreaOsk** [comment]
I have set up a project in Figma and sent you an invite.

**Comment by vilbergs** [comment]
I think this is a good issue to discuss the initial features we want to develop for the project.

## Background

As a home owner I want to have a centralized overview of all the different aspects of maintaining a home, garden and property in general. These can be information about individual rooms, checklists and statistics

### Initial features

#### Rooms

- An overview of the rooms and their measurements
- Later: temperature data from IoT network

#### Garden

- What is in the ground and when was it planted
- Planting and harvest timers 

#### Plumbing / Heating

- Average temperature in the whole house
- Temperature outliers (where is it cold)
- Water levels in well

**Comment by AndreaOsk** [comment]
### Sturcture

**How about grouping these into 3 tabs for now?** 

1. Home
2. Garden
3. Grounds (for example well info and outbuildings etc.) 

### Data

**Data to compile**
What are the best ways of compiling Data such as sowing and harvesting timelines for the garden? 
Should I start writing this info into a spreadsheet? 

**Open source data**
Is there any open source data available for things like local weather? 
Climate zones will affect showing and harvest times.

**Comment by AndreaOsk** [comment]
Wireframe created [here](https://www.figma.com/file/VklxnXCLGoj6QcqxqXVakd/Homebase?node-id=0%3A1)
